name: vetas
channels:
    - conda-forge
    - defaults
dependencies:
    - Fiona==1.8.21
    - gdal==3.5.2
    - geopandas==0.11.0
    - munch==2.5.0
    - numpy==1.23.1
    - packaging==21.3
    - pandas==1.4.3
    - pyparsing==3.0.9
    - pyproj==3.3.1
    - pytz==2022.1
    - scipy==1.8.1
    - Shapely==1.8.2
